### ISSUE TITLE
Build tool failing, it's trying to compile something i don't want.

### ISSUE THREAD

**Issue by Almightygir** [ryanjon2040/Unreal-Binary-Builder#35]
Hi there,

Attached are screenshots of the build tool and the settings I'm using, along with the errors. But it seems that the build tool is trying to build for LinuxArm64 even though I don't want/need it to.

![image](https://user-images.githubusercontent.com/6026593/124438234-d768a580-dd6f-11eb-9e39-c8a8693cd008.png)
![image](https://user-images.githubusercontent.com/6026593/124438245-db94c300-dd6f-11eb-937a-d0680f89ca70.png)

**Comment by ryanjon2040** [comment]
Hi there, Can you post the commandline? Use `Copy Commandline to clipboard` button

**Comment by Almightygir** [comment]
BuildGraph -target="Make Installed Build Win64" -script=Engine/Build/InstalledEngineBuild.xml -set:WithDDC=true -set:SignExecutables=false -set:EmbedSrcSrvInfo=false -set:GameConfigurations=Development;Shipping -set:WithFullDebugInfo=false -set:HostPlatformEditorOnly=false -set:AnalyticsTypeOverride= -set:HostPlatformDDCOnly=true -set:WithWin64=true -set:WithMac=false -set:WithAndroid=false -set:WithIOS=false -set:WithTVOS=false -set:WithLinux=false -set:WithLumin=false -set:WithLinuxAArch64=false -set:CompileDatasmithPlugins=false -set:WithServer=false -set:WithClient=false -set:WithHoloLens=false

**Comment by Almightygir** [comment]
After installing from here things seem to be going much more smoothly: https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.1.0

Still not sure why it's even attempting to compile anything for Linux, but I'll just take "working" for now, as it's UE5.

**Comment by Almightygir** [comment]
Looking earlier in the log, there's also this: WARNING: Unknown argument 'WithLinuxAArch64' for 'D:\KAOS\EngineSource\Engine\Build\InstalledEngineBuild.xml'

**Comment by Almightygir** [comment]
I found this line in `\Engine\Build\InstalledEngineBuild.xml`:
<Property Name="DefaultWithLinuxArm64" Value="true"/>

And changed the default value to false. This seems to have let me at least build. So at this stage I'm not sure if this is a problem with the binary builder (I compiled previously with VS2019 and had no issues). But maybe this knowledge will help someone else in future?

**Comment by ryanjon2040** [comment]
Have you modified the InstalledEngineBuild.xml in anyway? May I know which commit you are trying to build? The `LinuxAArch64` was removed in UE5 and they added LinuxArm64 which I have not added into Unreal Binary Builder yet. But still that value should be false by default and I have not encountered this error while building the Engine (I use ue-main branch).

**Comment by Almightygir** [comment]
I'm building UE5-main.

I haven't touched anything, just pulled from git and built.

**Comment by ryanjon2040** [comment]
That's strange. I'm also building from ue5-main but never had this issue. Anyways glad you sorted it out. I'm closing this for now.
