### ISSUE TITLE
Windows defender flags as trojan

### ISSUE THREAD

**Issue by nextrealm** [ryanjon2040/Unreal-Binary-Builder#36]
Windows defender flags the release zip as Trojan:Script/Oneeva.A!ml

**Comment by ryanjon2040** [comment]
Hi @nextrealm Thank you for the report. Yeah unfortunately Microsoft flags this as Trojan but it is false positive. I guarantee you the app is clean. I suspect the reason is because of either analytics or sentry. One of those might be triggering this false positive. I'm closing this for now.
