### ISSUE TITLE
Builds fail due to incorrect parameter value in CLI string

### ISSUE THREAD

**Issue by sansumbrella** [ryanjon2040/Unreal-Binary-Builder#41]
When attempting to build a version of UE4 based on 4.26 or 4.27 from Github, I run into an error around the build parameters:
`ERROR: C:\src\UnrealEngine\Engine\Build\InstalledEngineBuild.xml(61): 'true-set:WithWin32=true' is not a valid value for 'HostPlatformDDCOnly' (required: 'true|false')`

You will notice that the copied command-line includes the chunk `-set:HostPlatformDDCOnly=true-set:WithWin32=true`. This makes me think there is a missing space somewhere in the string concatenation used to generate the command.

```
BuildGraph -target="Make Installed Build Win64" -script=Engine/Build/InstalledEngineBuild.xml -set:WithDDC=true -set:SignExecutables=false -set:EmbedSrcSrvInfo=false -set:GameConfigurations=Development;Shipping -set:WithFullDebugInfo=false -set:HostPlatformEditorOnly=false -set:AnalyticsTypeOverride= -set:HostPlatformDDCOnly=true-set:WithWin32=true -set:WithWin64=true -set:WithMac=false -set:WithAndroid=false -set:WithIOS=false -set:WithTVOS=false -set:WithLinux=false -set:WithLumin=false -set:WithLinuxAArch64=false -set:CompileDatasmithPlugins=false -set:VS2019=true -set:WithServer=false -set:WithClient=false -set:WithHoloLens=false
```
I poked around the `Commandlines +=` sections of the code, but didn't find anything obvious to fix. Thanks!

**Comment by ryanjon2040** [comment]
Hi @sansumbrella 

> The issue has already been resolved. See #39
