### ISSUE TITLE
Threaded compile?

### ISSUE THREAD

**Issue by decryptedchaos** [ryanjon2040/Unreal-Binary-Builder#42]
I'm attempting to use this tool to create a binary build as its name entails.  

But it's been compileing for over 72 hours averaging 20% CPU UE source builds slow in normal cases.  but even then i can build it in VS in about 12 hours.   

This tool has been running for days and is only in stage 4/15,   So I'm wondering if its not leveraging all CPU cores.

**Comment by decryptedchaos** [comment]
We'll see i guess,  But even with ONLY Win64 selected,  it's still been running for 19 hours

**Comment by ryanjon2040** [comment]
I'm closing this issue for now. Feel free to comment if required.
