### ISSUE TITLE
Missing IOS dependency even though it's a excluded platform. 

### ISSUE THREAD

**Issue by decryptedchaos** [ryanjon2040/Unreal-Binary-Builder#43]
Well after 48 hours of compiling,  I've seen this issue posted once before with no solution and no attempt to investigate further. 

I have no apple products no apple software,  no apple/IOS anything  IOS is explicitly disabled and excluded from the build.  

With all due respect,  this has to be a an issue with UBB passing incorrect build CLI parameters.   IF UE builds normally without issue,   See i'm not familure with the CLI parms so i can't say what is causing it,   but i do know that if i build from VS this doesn't happen..  

Again,,  Win64 platform only  no client no server nothing.   this happens.  

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "BouncyCastle.Crypto". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [V:\UnrealEngine-4.26-chaos\Engine\Saved\CsTools\Engine\Source\Programs\IOS\iPhonePackager\iPhonePackager.csproj]`

`V:\UnrealEngine-4.26-chaos\Engine\Saved\CsTools\Engine\Source\Programs\IOS\iPhonePackager\Properties\Resources.resx(123,5): error MSB3103: Invalid Resx file. Could not find a part of the path 'V:\UnrealEngine-4.26-chaos\Engine\Saved\CsTools\Engine\Source\Programs\IOS\iPhonePackager\Resources\GreyCheck.png'. Line 123, position 5. [V:\UnrealEngine-4.26-chaos\Engine\Saved\CsTools\Engine\Source\Programs\IOS\iPhonePackager\iPhonePackager.csproj]`

**Comment by ryanjon2040** [comment]
Again, this is not an issue with UBB. If you don't like to use UBB then select your required options and press `Copy Commandline to Clipboard`. You can then go through the commandline, make sure everything is correct and manually run `AutomationToolLauncher.exe` with the copied commandline from windows terminal (like cmd or powershell). I've seen this compile error related to iPhonePackager before in ue5-main and Epic already fixed it. Before that I had to manually remove the `iPhonePackager.csproj` from under `Build Cs Tools` in `InstalledEngineBuild.xml`. And FYI, the error where it says `GreyCheck.png` is not the only one you will get. I faked that png with a simple paint image and then the errors were YellowCheck.png and GreenCheck.png not found.
