### ISSUE TITLE
Zipping engine folder does not show completed state

### ISSUE THREAD

**Issue by ImagineTheGames** [ryanjon2040/Unreal-Binary-Builder#45]
![image](https://user-images.githubusercontent.com/35975464/140779294-0e1d56b0-e3f3-420e-a3b2-2af3f2182b3e.png)

**Comment by ryanjon2040** [comment]
Hi @ImagineTheGames Can you explain what the issue is? In the log it says `Done zipping` which indicates the zipping has been completed.

**Comment by ImagineTheGames** [comment]
the progress bar is still moving 
![image](https://user-images.githubusercontent.com/35975464/140794854-bfb9cd2c-fa33-4996-9abb-951c2e53b361.png)
I expected this to clear after it was done?

**Comment by ryanjon2040** [comment]
Oh yeah that 😄 Sorry about that. You are right. I'll make sure to hide that once the zipping is done. Thanks man 👍🏼

**Comment by ImagineTheGames** [comment]
nothing to be sorry about.. thanks for the great tool

**Comment by ryanjon2040** [comment]
Hi @ImagineTheGames 

I've pushed a commit which should hide the progress bar. Thank you for letting me know! 🙂
