### ISSUE TITLE
Getting Chinese characters on English language setting

### ISSUE THREAD

**Issue by RobertPotter** [ryanjon2040/Unreal-Binary-Builder#53]
![image](https://user-images.githubusercontent.com/7904901/151656096-001cc884-05ad-46cb-98b6-7f53e6f13bf7.png)

**Comment by namrog84** [comment]
Same issue for me in latest 3.1.5

**Comment by Ares9323** [comment]
Other popup but same buttons, probably they're fixed text and not a localized text.
![image](https://user-images.githubusercontent.com/46932745/154864204-39c69df8-e96b-481b-82da-d92039e66596.png)

**Comment by ryanjon2040** [comment]
@RobertPotter @namrog84 @PhoenixStardash @Ares9323 Sorry for this. I reverted the package to an older version for now, so [current release](https://github.com/ryanjon2040/Unreal-Binary-Builder/releases) will have English text.
